server:
  port: 8081
spring:
  application:
    name: test-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_test_demo?serverTimezone=GMT%2B8
    username: root
    password: root
mybatis:
  type-aliases-package: com.rexyn.weifuwu.entity
  mapper-locations: classpath:mapper/*.xml