spring:
  application:
    name: payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_test_demo
    username: root
    password: root
server:
  port: 8001
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.rexyn.weifuwu.entity
