server:
  port: 8001

spring:
  application:
    name: service #服务名称
  datasource:
    #    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    #        driver-class-name: com.mysql.cj.jdbc.Driver
    #        url: jdbc:mysql://localhost:3306/my_test_demo?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    #        username: root
    #        password: root
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://localhost:3306/sheldon?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
#    spring.datasource.druid.read.driverClassName = com.mysql.cj.jdbc.Driver
#    spring.datasource.druid.read.url=jdbc:mysql://localhost:3306/mydb?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
#    spring.datasource.druid.read.username=root
#    spring.datasource.druid.read.password=123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo1.com.sheldon.mapper  #所有entity别名所在包
